/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  jc.ruiz
 * Created: 29/09/2017
 */

delete from ArtistaEntity;
delete from InfoEntity;
delete from ViniloEntity;
delete from CarroComprasEntity;
delete from TarjetaEntity;
delete from FeedBackEntity;
delete from ProveedorEntity;
delete from UsuarioEntity;
delete from CancionEntity;

insert into ProveedorEntity (id, name, email) values (46, 'Filmore', 'fsilverwood19@fotki.com');
insert into ProveedorEntity (id, name, email) values (47, 'Guillermo', 'gkille1a@latimes.com');
insert into ProveedorEntity (id, name, email) values (48, 'Trev', 'tpyford1b@i2i.jp');
insert into ProveedorEntity (id, name, email) values (49, 'Delmar', 'dcornu1c@hibu.com');
insert into ProveedorEntity (id, name, email) values (50, 'Shelba', 'satteridge1d@globo.com');
insert into ProveedorEntity (id, name, email) values (51, 'Toinette', 'tsurcombe1e@wikispaces.com');
insert into ProveedorEntity (id, name, email) values (52, 'Jessalyn', 'jpeyzer1f@cpanel.net');
insert into ProveedorEntity (id, name, email) values (53, 'Missie', 'madam1g@youtu.be');
insert into ProveedorEntity (id, name, email) values (54, 'Lenard', 'ldegiorgio1h@kickstarter.com');
insert into ProveedorEntity (id, name, email) values (55, 'Elenore', 'ekovalski1i@home.pl');
insert into ProveedorEntity (id, name, email) values (56, 'Goldia', 'gcalafato1j@lulu.com');
insert into ProveedorEntity (id, name, email) values (57, 'Claiborn', 'cfosher1k@icq.com');
insert into ProveedorEntity (id, name, email) values (58, 'Amie', 'alilleman1l@wp.com');
insert into ProveedorEntity (id, name, email) values (59, 'Tate', 'troebottom1m@yahoo.co.jp');
insert into ProveedorEntity (id, name, email) values (60, 'Andriette', 'asilversmidt1n@trellian.com');
insert into ProveedorEntity (id, name, email) values (61, 'Adelice', 'aillidge1o@hc360.com');
insert into ProveedorEntity (id, name, email) values (62, 'Blakelee', 'bparysiak1p@senate.gov');
insert into ProveedorEntity (id, name, email) values (63, 'Edyth', 'ejimson1q@sphinn.com');
insert into ProveedorEntity (id, name, email) values (64, 'David', 'dgooderson1r@buzzfeed.com');
insert into ProveedorEntity (id, name, email) values (65, 'Aurelia', 'ablueman1s@icio.us');
insert into ProveedorEntity (id, name, email) values (66, 'Ilyse', 'igirkin1t@ted.com');
insert into ProveedorEntity (id, name, email) values (67, 'Grantham', 'gcanet1u@imdb.com');
insert into ProveedorEntity (id, name, email) values (68, 'Vincent', 'vpiwell1v@scribd.com');
insert into ProveedorEntity (id, name, email) values (69, 'Henka', 'hpfaffel1w@facebook.com');
insert into ProveedorEntity (id, name, email) values (70, 'Cordelie', 'cfernanando1x@home.pl');
insert into ProveedorEntity (id, name, email) values (71, 'Kele', 'kotierney1y@bloglines.com');
insert into ProveedorEntity (id, name, email) values (72, 'Meade', 'mporter1z@deliciousdays.com');
insert into ProveedorEntity (id, name, email) values (73, 'Brook', 'bnears20@arizona.edu');
insert into ProveedorEntity (id, name, email) values (74, 'Fey', 'fallam21@netlog.com');
insert into ProveedorEntity (id, name, email) values (75, 'Cele', 'clambe22@fc2.com');
insert into ProveedorEntity (id, name, email) values (76, 'Oran', 'odunkerton23@i2i.jp');
insert into ProveedorEntity (id, name, email) values (77, 'Sancho', 'skerr24@cisco.com');
insert into ProveedorEntity (id, name, email) values (78, 'Lorrayne', 'lcapron25@ucoz.ru');
insert into ProveedorEntity (id, name, email) values (79, 'Skye', 'sblague26@a8.net');
insert into ProveedorEntity (id, name, email) values (80, 'Lance', 'lkaveney27@google.co.jp');
insert into ProveedorEntity (id, name, email) values (81, 'Catrina', 'cjurisic28@utexas.edu');
insert into ProveedorEntity (id, name, email) values (82, 'Malinda', 'madanet29@yale.edu');
insert into ProveedorEntity (id, name, email) values (83, 'Paulina', 'pearley2a@amazon.co.uk');
insert into ProveedorEntity (id, name, email) values (84, 'Marley', 'mmace2b@yahoo.com');
insert into ProveedorEntity (id, name, email) values (85, 'Ruby', 'rmcgurgan2c@ning.com');
insert into ProveedorEntity (id, name, email) values (86, 'Gare', 'gborton2d@sohu.com');
insert into ProveedorEntity (id, name, email) values (87, 'Shirley', 'spolye2e@scientificamerican.com');
insert into ProveedorEntity (id, name, email) values (88, 'Alleen', 'amccurtain2f@about.com');
insert into ProveedorEntity (id, name, email) values (89, 'Glenn', 'gexter2g@newsvine.com');
insert into ProveedorEntity (id, name, email) values (90, 'Cynthea', 'ccustance2h@netscape.com');
insert into ProveedorEntity (id, name, email) values (91, 'Juan', 'jmccathie2i@deviantart.com');
insert into ProveedorEntity (id, name, email) values (92, 'Arvy', 'acaldwell2j@privacy.gov.au');
insert into ProveedorEntity (id, name, email) values (93, 'Chicky', 'cfarrants2k@bloglovin.com');
insert into ProveedorEntity (id, name, email) values (94, 'Rupert', 'rmartins2l@psu.edu');
insert into ProveedorEntity (id, name, email) values (95, 'Andree', 'aterzi2m@163.com');
insert into ProveedorEntity (id, name, email) values (96, 'Cherrita', 'csarre2n@upenn.edu');
insert into ProveedorEntity (id, name, email) values (97, 'Bobbee', 'blemoucheux2o@cafepress.com');
insert into ProveedorEntity (id, name, email) values (98, 'Emmalyn', 'ecaplan2p@sohu.com');
insert into ProveedorEntity (id, name, email) values (99, 'Ken', 'kbollard2q@thetimes.co.uk');
insert into ProveedorEntity (id, name, email) values (100, 'Lizabeth', 'legger2r@soup.io');

insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (51, 'Fix San', 2008, 882.7, 51, 46);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (52, 'It', 1993, 869.2, 52, 46);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (53, 'Lotlux', 2012, 585.3, 53, 46);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (54, 'Otcom', 1985, 104.8, 54, 47);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades,proveedor_id) values (55, 'Stringtough', 2006, 693.4, 30, 47);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (56, 'Tin', 2008, 957.4, 20, 48);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (57, 'Transcof', 2000, 90.0, 50, 49);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (58, 'Overhold', 1992, 63.8, 58,50);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (59, 'Vagram', 2005, 440.4, 59,51);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (60, 'Subin', 2000, 192.5, 60,52);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (61, 'Alphazap', 2011, 329.5, 61,53);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (62, 'Duobam', 1993, 362.9, 62,54);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (63, 'Zaam-Dox', 2004, 323.9, 63,55);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (64, 'Alphazap', 2005, 538.4, 64,56);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (65, 'Wrapsafe', 2008, 855.8, 65,57);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (66, 'Vagram', 2006, 971.4, 66,58);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (67, 'Zamit', 1993, 320.4, 67,59);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (68, 'Flowdesk', 2012, 858.4, 68,60);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (69, 'Holdlamis', 2007, 451.2, 69,61);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (70, 'Sonair', 1991, 623.3, 70,62);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (71, 'Zaam-Dox', 1992, 877.8, 71,63);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (72, 'Stringtough', 1998, 573.7, 72,64);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (73, 'Domainer', 2012, 207.2, 73,65);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (74, 'Latlux', 1994, 925.6, 74,66);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (75, 'Matsoft', 2004, 739.5, 75,67);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (76, 'Regrant', 2009, 417.6, 76,68);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (77, 'Treeflex', 2012, 65.2, 77,69);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (78, 'Viva', 2007, 315.2, 78,70);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (79, 'Greenlam', 1978, 610.6, 79,71);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (80, 'Keylex', 1988, 602.6, 80,72);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (81, 'Lotstring', 1989, 944.6, 81,73);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (82, 'Tres-Zap', 2010, 512.3, 82,74);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (83, 'Veribet', 2012, 122.1, 83,75);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (84, 'Stim', 2011, 900.6, 84,76);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (85, 'Veribet', 1986, 833.2, 85,77);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (86, 'Greenlam', 2000, 45.3, 86,78);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (87, 'Trippledex', 2002, 300.4, 87,79);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (88, 'Konklab', 2011, 808.7, 88,80);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (89, 'Toughjoyfax', 1999, 935.0, 89,81);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (90, 'Bamity', 2008, 785.7, 90,82);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (91, 'Bitwolf', 2009, 559.8, 91,83);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (92, 'Flowdesk', 2010, 447.5, 92,84);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (93, 'Subin', 2007, 15.9, 93,85);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (94, 'Veribet', 2005, 897.9, 94,86);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (95, 'Aerified', 2010, 16.6, 95,87);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (96, 'Tres-Zap', 2004, 3.0, 96,88);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (97, 'Alpha', 2008, 869.7, 97,89);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (98, 'Alphazap', 2007, 454.0, 98,90);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (99, 'Cardguard', 2003, 89.8, 99,91);
insert into ViniloEntity (id, nombre, anio, precio, cantUnidades, proveedor_id) values (100, 'Veribet', 2001, 940.5, 100,92);

insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (51, 'Edyth', 'Gowlett', 'egowlett1e@histats.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (52, 'Antonia', 'Loghan', 'aloghan1f@google.es');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (53, 'Fernandina', 'Gasperi', 'fgasperi1g@chronoengine.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (54, 'Myrilla', 'Bineham', 'mbineham1h@drupal.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (55, 'Spense', 'Grand', 'sgrand1i@mit.edu');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (56, 'Oriana', 'McPhillimey', 'omcphillimey1j@huffingtonpost.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (57, 'Chrissy', 'Londing', 'clonding1k@amazon.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (58, 'Nicolis', 'Lynskey', 'nlynskey1l@vistaprint.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (59, 'Olimpia', 'Hallmark', 'ohallmark1m@nbcnews.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (60, 'Juieta', 'Costello', 'jcostello1n@army.mil');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (61, 'Minda', 'Buckley', 'mbuckley1o@phoca.cz');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (62, 'Jimmy', 'Sofe', 'jsofe1p@ucla.edu');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (63, 'Farris', 'Antrack', 'fantrack1q@ucoz.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (64, 'Jeffie', 'Bosence', 'jbosence1r@fema.gov');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (65, 'Cleavland', 'Salmon', 'csalmon1s@youtube.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (66, 'Mackenzie', 'Wilcox', 'mwilcox1t@wix.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (67, 'Lacie', 'Gussie', 'lgussie1u@barnesandnoble.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (68, 'Bibby', 'Losselyong', 'blosselyong1v@marriott.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (69, 'Philippa', 'Fidgett', 'pfidgett1w@seattletimes.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (70, 'Micheil', 'Mallabon', 'mmallabon1x@un.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (71, 'Joleen', 'Roth', 'jroth1y@fotki.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (72, 'Ealasaid', 'Kemson', 'ekemson1z@prlog.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (73, 'Raleigh', 'Aylwin', 'raylwin20@mayoclinic.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (74, 'Karissa', 'Mc Menamin', 'kmcmenamin21@salon.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (75, 'Vivianne', 'Bowsher', 'vbowsher22@blogspot.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (76, 'Jephthah', 'Whiteman', 'jwhiteman23@blogs.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (77, 'Corissa', 'Jendrusch', 'cjendrusch24@odnoklassniki.ru');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (78, 'Reinold', 'Faint', 'rfaint25@unesco.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (79, 'Glen', 'Mapples', 'gmapples26@ycombinator.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (80, 'Heall', 'Januszewicz', 'hjanuszewicz27@usa.gov');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (81, 'Tiffie', 'Biaggiotti', 'tbiaggiotti28@bbc.co.uk');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (82, 'Marillin', 'Aleixo', 'maleixo29@archive.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (83, 'Winne', 'Hawsby', 'whawsby2a@boston.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (84, 'Chandler', 'Deguara', 'cdeguara2b@bravesites.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (85, 'Peder', 'Strete', 'pstrete2c@cbc.ca');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (86, 'Nelly', 'MacAllester', 'nmacallester2d@shutterfly.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (87, 'Analiese', 'Blackall', 'ablackall2e@msu.edu');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (88, 'Gannon', 'Vasilov', 'gvasilov2f@mozilla.org');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (89, 'Othella', 'Quinney', 'oquinney2g@loc.gov');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (90, 'Francine', 'Cambell', 'fcambell2h@rakuten.co.jp');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (91, 'Stanwood', 'Cordey', 'scordey2i@elegantthemes.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (92, 'Janaya', 'Taylder', 'jtaylder2j@posterous.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (93, 'Horace', 'Pimm', 'hpimm2k@parallels.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (94, 'Arabel', 'Proffitt', 'aproffitt2l@nhs.uk');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (95, 'Ulla', 'McCafferky', 'umccafferky2m@163.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (96, 'Mady', 'Martino', 'mmartino2n@friendfeed.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (97, 'Chas', 'Turfitt', 'cturfitt2o@google.com.hk');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (98, 'Renee', 'Jeannard', 'rjeannard2p@msn.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (99, 'Herrick', 'Smeaton', 'hsmeaton2q@nymag.com');
insert into InfoEntity (id, urlImagen, urlCancion, descripcion) values (100, 'Courtnay', 'Hedon', 'chedon2r@scribd.com');

insert into ArtistaEntity (id, name) values (500, 'Gavan');
insert into ArtistaEntity (id, name) values (501, 'Randal');
insert into ArtistaEntity (id, name) values (502, 'Abagail');
insert into ArtistaEntity (id, name) values (503, 'Efrem');
insert into ArtistaEntity (id, name) values (504, 'Wilona');
insert into ArtistaEntity (id, name) values (505, 'Ellary');
insert into ArtistaEntity (id, name) values (506, 'Jasmina');

insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (51, 19, 'echidwick1e@naver.com', 69, '5/17/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (52, 73, 'cwaiton1f@privacy.gov.au', 58, '8/30/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (53, 23, 'bmusla1g@cbslocal.com', 94, '3/29/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (54, 76, 'mbendel1h@nydailynews.com', 47, '11/4/2016');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (55, 8, 'sshoosmith1i@mtv.com', 27, '8/17/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (56, 7, 'egrimsley1j@who.int', 73, '7/27/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (57, 7, 'aosirin1k@acquirethisname.com', 6, '2/10/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (58, 2, 'abullen1l@biglobe.ne.jp', 89, '2/16/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (59, 17, 'ipfeffel1m@illinois.edu', 89, '8/31/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (60, 71, 'emcewen1n@soup.io', 50, '9/20/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (61, 32, 'wcaldow1o@princeton.edu', 89, '7/30/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (62, 69, 'dburnall1p@walmart.com', 54, '3/6/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (63, 62, 'pbarstow1q@whitehouse.gov', 4, '8/27/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (64, 51, 'nridolfi1r@accuweather.com', 49, '7/30/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (65, 31, 'bewbanks1s@jalbum.net', 13, '6/29/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (66, 89, 'jleadley1t@shinystat.com', 49, '6/20/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (67, 32, 'pcalken1u@bizjournals.com', 82, '11/7/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (68, 14, 'cfawdrey1v@psu.edu', 57, '6/1/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (69, 33, 'nvarvara1w@over-blog.com', 83, '11/26/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (70, 43, 'grousel1x@who.int', 74, '4/12/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (71, 71, 'mmolloy1y@furl.net', 80, '11/18/2016');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (72, 61, 'jhazzard1z@virginia.edu', 90, '4/10/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (73, 27, 'shigginbottam20@cargocollective.com', 9, '8/28/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (74, 89, 'gnesfield21@alibaba.com', 85, '6/1/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (75, 96, 'icattrall22@alibaba.com', 52, '9/27/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (76, 92, 'csoot23@fema.gov', 7, '5/18/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (77, 12, 'etotton24@sciencedaily.com', 64, '9/8/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (78, 80, 'hmaccroary25@uiuc.edu', 24, '9/27/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (79, 78, 'lcraiker26@nbcnews.com', 14, '5/18/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (80, 60, 'tdunbabin27@amazon.de', 26, '5/15/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (81, 58, 'escrimshaw28@mapy.cz', 63, '12/12/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (82, 90, 'spiens29@ucoz.com', 98, '4/24/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (83, 6, 'abrussell2a@ft.com', 9, '3/17/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (84, 94, 'wroset2b@infoseek.co.jp', 84, '4/28/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (85, 98, 'dbonniface2c@hugedomains.com', 93, '9/13/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (86, 67, 'pbotger2d@forbes.com', 34, '1/23/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (87, 68, 'icasarino2e@sciencedirect.com', 34, '7/31/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (88, 1, 'ssiemandl2f@is.gd', 38, '5/25/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (89, 44, 'cbohlens2g@instagram.com', 24, '10/12/2016');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (90, 56, 'fbream2h@imageshack.us', 1, '5/2/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (91, 26, 'abubbings2i@biblegateway.com', 10, '5/12/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (92, 69, 'dbiers2j@chron.com', 3, '4/22/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (93, 39, 'mlearoyde2k@economist.com', 75, '8/7/2017');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (94, 21, 'pgrigoroni2l@cdc.gov', 23, '5/10/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (95, 68, 'wlemin2m@blinklist.com', 24, '3/10/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (96, 68, 'cgeertz2n@webeden.co.uk', 35, '10/6/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (97, 20, 'bosborne2o@digg.com', 69, '6/27/2020');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (98, 73, 'mgaynes2p@ibm.com', 53, '4/30/2018');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (99, 40, 'kcanniffe2q@163.com', 72, '7/16/2019');
insert into TarjetaEntity (id, numero, nombrePropietario, cvc, goodThru) values (100, 94, 'bjancso2r@omniture.com', 40, '9/14/2017');

insert into UsuarioEntity (id, name, eMail, cantCompras) values (943, 'Katlin', 'kdooganq6@reference.com', 49);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (944, 'Reidar', 'rparffreyq7@cafepress.com', 77);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (945, 'Nicholas', 'ngirdlestoneq8@sourceforge.net', 66);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (946, 'Aimee', 'aciscoq9@ucoz.ru', 74);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (947, 'Chadwick', 'cfischerqa@businessinsider.com', 1);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (948, 'Brigid', 'bmathonnetqb@fda.gov', 9);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (949, 'Nancee', 'nolageneqc@ftc.gov', 2);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (950, 'Cam', 'clesserqd@t.co', 42);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (951, 'Onfroi', 'oburnsallqe@elpais.com', 34);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (952, 'Rubina', 'rtromanqf@guardian.co.uk', 29);
insert into UsuarioEntity (id, name, eMail, cantCompras) values (953, 'Caralie', 'cparsonsqg@latimes.com', 61);

insert into CarroComprasEntity (id,precioTotal,USUARIO_ID) values (900,13000,943);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (31, 111090, 944);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (32, 138211, 945);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (33, 210487, 946);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (34, 502831, 947);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (35, 134501, 948);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (36, 647610, 949);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (37, 564599, 950);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (38, 139647, 951);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (39, 54193, 952);
insert into CarroComprasEntity (id, precioTotal,USUARIO_ID) values (40, 169156, 953);

insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (44, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante', 2.7, 46);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (45, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 3.3,47);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (46, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 2.1,46);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (47, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 2.0,47);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (48, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 3.2,48);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (49, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', 4.4,48);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (50, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', 4.1,49);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (51, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 2.8,50);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (52, 'sapien non mi integer ac neque duis bibendum morbi non', 3.3,51);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id)  values (53, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 3.1,51);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (54, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 1.1, 98);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (55, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 1.4, 52);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (56, 'magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 4.7, 59);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (57, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 3.6,60);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (58, 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 3.6, 61);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (59, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 1.7, 62);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (60, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 3.6, 63);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (61, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 3.4, 64);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (62, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 1.3, 65);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (63, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit', 3.3, 66);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (64, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu', 2.7, 67);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (65, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 4.1, 68);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (66, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 5.0, 69);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (67, 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 3.5, 70);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (68, 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 2.3, 71);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (69, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 1.3, 72);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (70, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 3.7, 73);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (71, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 3.1, 74);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (72, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', 2.8, 75);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (73, 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 1.0, 76);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (74, 'ut erat curabitur gravida nisi at nibh in hac habitasse', 1.2, 77);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (75, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 4.5, 52);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (76, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 2.2, 53);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (77, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', 4.5, 54);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (78, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 1.9, 55);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (79, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit', 3.0, 56);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (80, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 2.6, 78);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (81, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 1.7, 79);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (82, 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 3.9, 80);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (83, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 4.3, 81);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (84, 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 2.1, 82);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (85, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 1.9, 83);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (86, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 3.3, 84);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (87, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', 2.7, 85);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (88, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 4.7, 86);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (89, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 2.0, 87);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (90, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis', 2.5, 88);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (91, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 2.9, 89);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (92, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 4.9, 90);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (93, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 2.3, 91);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (94, 'aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 3.6, 92);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (95, 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 2.9, 93);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (96, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', 1.7, 94);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (97, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 2.4, 95);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (98, 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 3.3, 96);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (99, 'proin leo odio porttitor id consequat in consequat ut nulla sed', 2.7, 97);
insert into FeedBackEntity (id, comentario, calificacion, proveedor_id) values (100, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 2.4, 98);


delete from PedidoProveedorEntity;
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (1, '2013-08-30 19:05:00' , '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (2, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (3, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (4,'2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (5, '2013-08-30 19:05:00', '', 882.);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (6, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (7, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (8, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (9, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (10, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (11, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (12, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (13, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (14, '2013-08-30 19:05:00', '', 882.7);

insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (16, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (17, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (18, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (19,'2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (20, '2013-08-30 19:05:00', '', 882.7);
insert into PedidoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (21, '2013-08-30 19:05:00', '', 882.7);


delete from PagoProveedorEntity;
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (1, '2013-08-30 19:05:00' , '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (2, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (3, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (4,'2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (5, '2013-08-30 19:05:00', '', 882.);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (6, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (7, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (8, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (9, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (10, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (11, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (12, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (13, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (14, '2013-08-30 19:05:00', '', 882.7);

insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (16, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (17, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (18, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (19,'2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (20, '2013-08-30 19:05:00', '', 882.7);
insert into PagoProveedorEntity (ID, FECHAESTIMADA, NAME, PRECIO) values (21, '2013-08-30 19:05:00', '', 882.7);


insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(100,8,'https://open.spotify.com/embed?uri=spotify:track:2fuCquhmrzHpu5xcA1ci9x','Under Pressure',500,51);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(101,8,'https://open.spotify.com/embed?uri=spotify:track:1AhDOtG9vPSOmsWgNW0BEY','Bohemian Rapsody',500,51);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(102,5,'https://open.spotify.com/embed?uri=spotify:track:7qiZfU4dY1lWllzX7mPBI3','Shape of you',500,52);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(103,6,'https://open.spotify.com/embed?uri=spotify:track:0tgVpDi06FyKpA1z0VMD4v','Perfect',500,52);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(104,5,'https://open.spotify.com/embed?uri=spotify:track:2hYlWnPvVZtQZGWfb35HPQ','Im not the only one',500,53);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(105,6,'https://open.spotify.com/embed?uri=spotify:track:2whoe0pPKh4JRn6eWSIqTV','Stay with me',500,53);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(106,5,'https://open.spotify.com/embed?uri=spotify:track:1I8tHoNBFTuoJAlh4hfVVE','Stole the show',500,54);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(107,6,'https://open.spotify.com/embed?uri=spotify:track:5masKPHeAOVNgxdLebIcK7','Firestone',500,54);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(108,5,'https://open.spotify.com/embed?uri=spotify:track:0uuEqOyKlABOB7hzWKcEeG','A las Nueve',500,55);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(109,6,'https://open.spotify.com/embed?uri=spotify:track:7D5yebasDybJ83PTpwQNfx','Tan lejos',500,55);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(110,8,'https://open.spotify.com/embed?uri=spotify:track:2fuCquhmrzHpu5xcA1ci9x','Under Pressure',500,56);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(111,8,'https://open.spotify.com/embed?uri=spotify:track:1AhDOtG9vPSOmsWgNW0BEY','Bohemian Rapsody',500,56);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(112,5,'https://open.spotify.com/embed?uri=spotify:track:7qiZfU4dY1lWllzX7mPBI3','Shape of you',500,57);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(113,6,'https://open.spotify.com/embed?uri=spotify:track:0tgVpDi06FyKpA1z0VMD4v','Perfect',500,57);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(114,5,'https://open.spotify.com/embed?uri=spotify:track:2hYlWnPvVZtQZGWfb35HPQ','Im not the only one',500,58);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(115,6,'https://open.spotify.com/embed?uri=spotify:track:2whoe0pPKh4JRn6eWSIqTV','Stay with me',500,58);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(116,5,'https://open.spotify.com/embed?uri=spotify:track:1I8tHoNBFTuoJAlh4hfVVE','Stole the show',500,59);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(117,6,'https://open.spotify.com/embed?uri=spotify:track:5masKPHeAOVNgxdLebIcK7','Firestone',500,59);

insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(118,5,'https://open.spotify.com/embed?uri=spotify:track:0uuEqOyKlABOB7hzWKcEeG','A las Nueve',500,60);
insert into Cancionentity (ID,DURACION,LINK,NAME,ARTISTAS_ID,VINILO_ID) values(119,6,'https://open.spotify.com/embed?uri=spotify:track:7D5yebasDybJ83PTpwQNfx','Tan lejos',500,60);