/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  jc.ruiz
 * Created: 24/09/2017
 */

delete from ProveedorEntity;
delete from FeedBackEntity;

insert into ProveedorEntity (id, name, email) values (1, 'Guthry', 'gfanstone0@tiny.cc');
insert into ProveedorEntity (id, name, email) values (2, 'Tyler', 'tdrinnan1@chronoengine.com');
insert into ProveedorEntity (id, name, email) values (3, 'Jean', 'jbonfield2@g.co');
insert into ProveedorEntity (id, name, email) values (4, 'Tana', 'tpettingall3@paypal.com');
insert into ProveedorEntity (id, name, email) values (5, 'Bobette', 'bmottini4@boston.com');
insert into ProveedorEntity (id, name, email) values (6, 'Marillin', 'mgrabbam5@blinklist.com');
insert into ProveedorEntity (id, name, email) values (7, 'Rooney', 'rquinell6@webnode.com');
insert into ProveedorEntity (id, name, email) values (8, 'Duffie', 'djaskowicz7@cornell.edu');
insert into ProveedorEntity (id, name, email) values (9, 'Louis', 'lcoghlin8@symantec.com');
insert into ProveedorEntity (id, name, email) values (10, 'Penny', 'pbatting9@amazonaws.com');
insert into ProveedorEntity (id, name, email) values (11, 'Erl', 'ekiehla@google.com.au');
insert into ProveedorEntity (id, name, email) values (12, 'Roda', 'rgurnerb@indiegogo.com');
insert into ProveedorEntity (id, name, email) values (13, 'Sloane', 'strahearnc@businesswire.com');
insert into ProveedorEntity (id, name, email) values (14, 'Grove', 'gsommerlyd@chronoengine.com');
insert into ProveedorEntity (id, name, email) values (15, 'Sterling', 'shassere@wiley.com');
insert into ProveedorEntity (id, name, email) values (16, 'Ara', 'ablackstonf@lycos.com');
insert into ProveedorEntity (id, name, email) values (17, 'Aaron', 'alowesg@mozilla.com');
insert into ProveedorEntity (id, name, email) values (18, 'Timoteo', 'tjahndelh@biblegateway.com');
insert into ProveedorEntity (id, name, email) values (19, 'Karl', 'ksenteri@techcrunch.com');
insert into ProveedorEntity (id, name, email) values (20, 'Valaree', 'vdelamainej@phoca.cz');
insert into ProveedorEntity (id, name, email) values (21, 'Dennie', 'dpartridgek@pagesperso-orange.fr');
insert into ProveedorEntity (id, name, email) values (22, 'Gilbertine', 'gsarfatil@yellowbook.com');
insert into ProveedorEntity (id, name, email) values (23, 'Annie', 'alarcierem@over-blog.com');
insert into ProveedorEntity (id, name, email) values (24, 'Shanna', 'sdubockn@surveymonkey.com');
insert into ProveedorEntity (id, name, email) values (25, 'Cchaddie', 'claurenceauo@pen.io');
insert into ProveedorEntity (id, name, email) values (26, 'Ebba', 'edawnayp@baidu.com');
insert into ProveedorEntity (id, name, email) values (27, 'Ofilia', 'ohynamq@ebay.com');
insert into ProveedorEntity (id, name, email) values (28, 'Joni', 'jgwinnelr@google.ru');
insert into ProveedorEntity (id, name, email) values (29, 'Sadie', 'snissles@marriott.com');
insert into ProveedorEntity (id, name, email) values (30, 'Odelinda', 'owhittletont@ibm.com');
insert into ProveedorEntity (id, name, email) values (31, 'Rodrick', 'rpirrieu@unicef.org');
insert into ProveedorEntity (id, name, email) values (32, 'Nerita', 'nstorrv@who.int');
insert into ProveedorEntity (id, name, email) values (33, 'Gusti', 'ggodlyw@acquirethisname.com');
insert into ProveedorEntity (id, name, email) values (34, 'Louie', 'lbartoschx@w3.org');
insert into ProveedorEntity (id, name, email) values (35, 'Noreen', 'nfarnally@washingtonpost.com');
insert into ProveedorEntity (id, name, email) values (36, 'Mabelle', 'mpaprotnyz@miitbeian.gov.cn');
insert into ProveedorEntity (id, name, email) values (37, 'Mendel', 'mchicchetto10@i2i.jp');
insert into ProveedorEntity (id, name, email) values (38, 'Rubin', 'rclaxton11@newyorker.com');
insert into ProveedorEntity (id, name, email) values (39, 'Valery', 'vbruckmann12@dot.gov');
insert into ProveedorEntity (id, name, email) values (40, 'Kacie', 'ksawney13@state.gov');
insert into ProveedorEntity (id, name, email) values (41, 'Vivyan', 'vlyttle14@wsj.com');
insert into ProveedorEntity (id, name, email) values (42, 'Sandy', 'ssmowton15@dropbox.com');
insert into ProveedorEntity (id, name, email) values (43, 'Nertie', 'nthurman16@state.tx.us');
insert into ProveedorEntity (id, name, email) values (44, 'Glyn', 'gpayler17@time.com');
insert into ProveedorEntity (id, name, email) values (45, 'Homerus', 'hphilipart18@google.ca');
insert into ProveedorEntity (id, name, email) values (46, 'Filmore', 'fsilverwood19@fotki.com');
insert into ProveedorEntity (id, name, email) values (47, 'Guillermo', 'gkille1a@latimes.com');
insert into ProveedorEntity (id, name, email) values (48, 'Trev', 'tpyford1b@i2i.jp');
insert into ProveedorEntity (id, name, email) values (49, 'Delmar', 'dcornu1c@hibu.com');
insert into ProveedorEntity (id, name, email) values (50, 'Shelba', 'satteridge1d@globo.com');
insert into ProveedorEntity (id, name, email) values (51, 'Toinette', 'tsurcombe1e@wikispaces.com');
insert into ProveedorEntity (id, name, email) values (52, 'Jessalyn', 'jpeyzer1f@cpanel.net');
insert into ProveedorEntity (id, name, email) values (53, 'Missie', 'madam1g@youtu.be');
insert into ProveedorEntity (id, name, email) values (54, 'Lenard', 'ldegiorgio1h@kickstarter.com');
insert into ProveedorEntity (id, name, email) values (55, 'Elenore', 'ekovalski1i@home.pl');
insert into ProveedorEntity (id, name, email) values (56, 'Goldia', 'gcalafato1j@lulu.com');
insert into ProveedorEntity (id, name, email) values (57, 'Claiborn', 'cfosher1k@icq.com');
insert into ProveedorEntity (id, name, email) values (58, 'Amie', 'alilleman1l@wp.com');
insert into ProveedorEntity (id, name, email) values (59, 'Tate', 'troebottom1m@yahoo.co.jp');
insert into ProveedorEntity (id, name, email) values (60, 'Andriette', 'asilversmidt1n@trellian.com');
insert into ProveedorEntity (id, name, email) values (61, 'Adelice', 'aillidge1o@hc360.com');
insert into ProveedorEntity (id, name, email) values (62, 'Blakelee', 'bparysiak1p@senate.gov');
insert into ProveedorEntity (id, name, email) values (63, 'Edyth', 'ejimson1q@sphinn.com');
insert into ProveedorEntity (id, name, email) values (64, 'David', 'dgooderson1r@buzzfeed.com');
insert into ProveedorEntity (id, name, email) values (65, 'Aurelia', 'ablueman1s@icio.us');
insert into ProveedorEntity (id, name, email) values (66, 'Ilyse', 'igirkin1t@ted.com');
insert into ProveedorEntity (id, name, email) values (67, 'Grantham', 'gcanet1u@imdb.com');
insert into ProveedorEntity (id, name, email) values (68, 'Vincent', 'vpiwell1v@scribd.com');
insert into ProveedorEntity (id, name, email) values (69, 'Henka', 'hpfaffel1w@facebook.com');
insert into ProveedorEntity (id, name, email) values (70, 'Cordelie', 'cfernanando1x@home.pl');
insert into ProveedorEntity (id, name, email) values (71, 'Kele', 'kotierney1y@bloglines.com');
insert into ProveedorEntity (id, name, email) values (72, 'Meade', 'mporter1z@deliciousdays.com');
insert into ProveedorEntity (id, name, email) values (73, 'Brook', 'bnears20@arizona.edu');
insert into ProveedorEntity (id, name, email) values (74, 'Fey', 'fallam21@netlog.com');
insert into ProveedorEntity (id, name, email) values (75, 'Cele', 'clambe22@fc2.com');
insert into ProveedorEntity (id, name, email) values (76, 'Oran', 'odunkerton23@i2i.jp');
insert into ProveedorEntity (id, name, email) values (77, 'Sancho', 'skerr24@cisco.com');
insert into ProveedorEntity (id, name, email) values (78, 'Lorrayne', 'lcapron25@ucoz.ru');
insert into ProveedorEntity (id, name, email) values (79, 'Skye', 'sblague26@a8.net');
insert into ProveedorEntity (id, name, email) values (80, 'Lance', 'lkaveney27@google.co.jp');
insert into ProveedorEntity (id, name, email) values (81, 'Catrina', 'cjurisic28@utexas.edu');
insert into ProveedorEntity (id, name, email) values (82, 'Malinda', 'madanet29@yale.edu');
insert into ProveedorEntity (id, name, email) values (83, 'Paulina', 'pearley2a@amazon.co.uk');
insert into ProveedorEntity (id, name, email) values (84, 'Marley', 'mmace2b@yahoo.com');
insert into ProveedorEntity (id, name, email) values (85, 'Ruby', 'rmcgurgan2c@ning.com');
insert into ProveedorEntity (id, name, email) values (86, 'Gare', 'gborton2d@sohu.com');
insert into ProveedorEntity (id, name, email) values (87, 'Shirley', 'spolye2e@scientificamerican.com');
insert into ProveedorEntity (id, name, email) values (88, 'Alleen', 'amccurtain2f@about.com');
insert into ProveedorEntity (id, name, email) values (89, 'Glenn', 'gexter2g@newsvine.com');
insert into ProveedorEntity (id, name, email) values (90, 'Cynthea', 'ccustance2h@netscape.com');
insert into ProveedorEntity (id, name, email) values (91, 'Juan', 'jmccathie2i@deviantart.com');
insert into ProveedorEntity (id, name, email) values (92, 'Arvy', 'acaldwell2j@privacy.gov.au');
insert into ProveedorEntity (id, name, email) values (93, 'Chicky', 'cfarrants2k@bloglovin.com');
insert into ProveedorEntity (id, name, email) values (94, 'Rupert', 'rmartins2l@psu.edu');
insert into ProveedorEntity (id, name, email) values (95, 'Andree', 'aterzi2m@163.com');
insert into ProveedorEntity (id, name, email) values (96, 'Cherrita', 'csarre2n@upenn.edu');
insert into ProveedorEntity (id, name, email) values (97, 'Bobbee', 'blemoucheux2o@cafepress.com');
insert into ProveedorEntity (id, name, email) values (98, 'Emmalyn', 'ecaplan2p@sohu.com');
insert into ProveedorEntity (id, name, email) values (99, 'Ken', 'kbollard2q@thetimes.co.uk');
insert into ProveedorEntity (id, name, email) values (100, 'Lizabeth', 'legger2r@soup.io');

insert into FeedBackEntity (id, comentario, calificacion) values (1, 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 2.4);
insert into FeedBackEntity (id, comentario, calificacion) values (2, 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui', 4.4);
insert into FeedBackEntity (id, comentario, calificacion) values (3, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 4.2);
insert into FeedBackEntity (id, comentario, calificacion) values (4, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1.9);
insert into FeedBackEntity (id, comentario, calificacion) values (5, 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', 4.3);
insert into FeedBackEntity (id, comentario, calificacion) values (6, 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 3.9);
insert into FeedBackEntity (id, comentario, calificacion) values (7, 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec', 1.7);
insert into FeedBackEntity (id, comentario, calificacion) values (8, 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et', 1.3);
insert into FeedBackEntity (id, comentario, calificacion) values (9, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', 1.3);
insert into FeedBackEntity (id, comentario, calificacion) values (10, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 2.1);
insert into FeedBackEntity (id, comentario, calificacion) values (11, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 1.5);
insert into FeedBackEntity (id, comentario, calificacion) values (12, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 2.2);
insert into FeedBackEntity (id, comentario, calificacion) values (13, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', 5.0);
insert into FeedBackEntity (id, comentario, calificacion) values (14, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', 1.4);
insert into FeedBackEntity (id, comentario, calificacion) values (15, 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 3.4);
insert into FeedBackEntity (id, comentario, calificacion) values (16, 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 3.4);
insert into FeedBackEntity (id, comentario, calificacion) values (17, 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', 2.0);
insert into FeedBackEntity (id, comentario, calificacion) values (18, 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', 3.6);
insert into FeedBackEntity (id, comentario, calificacion) values (19, 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', 1.8);
insert into FeedBackEntity (id, comentario, calificacion) values (20, 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 3.8);
insert into FeedBackEntity (id, comentario, calificacion) values (21, 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula', 2.5);
insert into FeedBackEntity (id, comentario, calificacion) values (22, 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 3.8);
insert into FeedBackEntity (id, comentario, calificacion) values (23, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 2.9);
insert into FeedBackEntity (id, comentario, calificacion) values (24, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', 3.0);
insert into FeedBackEntity (id, comentario, calificacion) values (25, 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 1.0);
insert into FeedBackEntity (id, comentario, calificacion) values (26, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 4.5);
insert into FeedBackEntity (id, comentario, calificacion) values (27, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 2.7);
insert into FeedBackEntity (id, comentario, calificacion) values (28, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', 3.0);
insert into FeedBackEntity (id, comentario, calificacion) values (29, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa', 2.5);
insert into FeedBackEntity (id, comentario, calificacion) values (30, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 1.2);
insert into FeedBackEntity (id, comentario, calificacion) values (31, 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 4.4);
insert into FeedBackEntity (id, comentario, calificacion) values (32, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 3.2);
insert into FeedBackEntity (id, comentario, calificacion) values (33, 'in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 2.6);
insert into FeedBackEntity (id, comentario, calificacion) values (34, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 4.3);
insert into FeedBackEntity (id, comentario, calificacion) values (35, 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta', 1.1);
insert into FeedBackEntity (id, comentario, calificacion) values (36, 'libero rutrum ac lobortis vel dapibus at diam nam tristique', 1.4);
insert into FeedBackEntity (id, comentario, calificacion) values (37, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 2.9);
insert into FeedBackEntity (id, comentario, calificacion) values (38, 'sed sagittis nam congue risus semper porta volutpat quam pede', 4.3);
insert into FeedBackEntity (id, comentario, calificacion) values (39, 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien', 4.2);
insert into FeedBackEntity (id, comentario, calificacion) values (40, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', 4.1);
insert into FeedBackEntity (id, comentario, calificacion) values (41, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', 3.1);
insert into FeedBackEntity (id, comentario, calificacion) values (42, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 3.2);
insert into FeedBackEntity (id, comentario, calificacion) values (43, 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam', 1.7);
insert into FeedBackEntity (id, comentario, calificacion) values (44, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante', 2.7);
insert into FeedBackEntity (id, comentario, calificacion) values (45, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 3.3);
insert into FeedBackEntity (id, comentario, calificacion) values (46, 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo', 2.1);
insert into FeedBackEntity (id, comentario, calificacion) values (47, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 2.0);
insert into FeedBackEntity (id, comentario, calificacion) values (48, 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 3.2);
insert into FeedBackEntity (id, comentario, calificacion) values (49, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', 4.4);
insert into FeedBackEntity (id, comentario, calificacion) values (50, 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', 4.1);
insert into FeedBackEntity (id, comentario, calificacion) values (51, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 2.8);
insert into FeedBackEntity (id, comentario, calificacion) values (52, 'sapien non mi integer ac neque duis bibendum morbi non', 3.3);
insert into FeedBackEntity (id, comentario, calificacion) values (53, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 3.1);
insert into FeedBackEntity (id, comentario, calificacion) values (54, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 1.1);
insert into FeedBackEntity (id, comentario, calificacion) values (55, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', 1.4);
insert into FeedBackEntity (id, comentario, calificacion) values (56, 'magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', 4.7);
insert into FeedBackEntity (id, comentario, calificacion) values (57, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 3.6);
insert into FeedBackEntity (id, comentario, calificacion) values (58, 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 3.6);
insert into FeedBackEntity (id, comentario, calificacion) values (59, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 1.7);
insert into FeedBackEntity (id, comentario, calificacion) values (60, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 3.6);
insert into FeedBackEntity (id, comentario, calificacion) values (61, 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 3.4);
insert into FeedBackEntity (id, comentario, calificacion) values (62, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', 1.3);
insert into FeedBackEntity (id, comentario, calificacion) values (63, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit', 3.3);
insert into FeedBackEntity (id, comentario, calificacion) values (64, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu', 2.7);
insert into FeedBackEntity (id, comentario, calificacion) values (65, 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 4.1);
insert into FeedBackEntity (id, comentario, calificacion) values (66, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 5.0);
insert into FeedBackEntity (id, comentario, calificacion) values (67, 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 3.5);
insert into FeedBackEntity (id, comentario, calificacion) values (68, 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', 2.3);
insert into FeedBackEntity (id, comentario, calificacion) values (69, 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 1.3);
insert into FeedBackEntity (id, comentario, calificacion) values (70, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 3.7);
insert into FeedBackEntity (id, comentario, calificacion) values (71, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 3.1);
insert into FeedBackEntity (id, comentario, calificacion) values (72, 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', 2.8);
insert into FeedBackEntity (id, comentario, calificacion) values (73, 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 1.0);
insert into FeedBackEntity (id, comentario, calificacion) values (74, 'ut erat curabitur gravida nisi at nibh in hac habitasse', 1.2);
insert into FeedBackEntity (id, comentario, calificacion) values (75, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 4.5);
insert into FeedBackEntity (id, comentario, calificacion) values (76, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 2.2);
insert into FeedBackEntity (id, comentario, calificacion) values (77, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', 4.5);
insert into FeedBackEntity (id, comentario, calificacion) values (78, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', 1.9);
insert into FeedBackEntity (id, comentario, calificacion) values (79, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit', 3.0);
insert into FeedBackEntity (id, comentario, calificacion) values (80, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 2.6);
insert into FeedBackEntity (id, comentario, calificacion) values (81, 'sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 1.7);
insert into FeedBackEntity (id, comentario, calificacion) values (82, 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 3.9);
insert into FeedBackEntity (id, comentario, calificacion) values (83, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 4.3);
insert into FeedBackEntity (id, comentario, calificacion) values (84, 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 2.1);
insert into FeedBackEntity (id, comentario, calificacion) values (85, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 1.9);
insert into FeedBackEntity (id, comentario, calificacion) values (86, 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 3.3);
insert into FeedBackEntity (id, comentario, calificacion) values (87, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', 2.7);
insert into FeedBackEntity (id, comentario, calificacion) values (88, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 4.7);
insert into FeedBackEntity (id, comentario, calificacion) values (89, 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 2.0);
insert into FeedBackEntity (id, comentario, calificacion) values (90, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis', 2.5);
insert into FeedBackEntity (id, comentario, calificacion) values (91, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 2.9);
insert into FeedBackEntity (id, comentario, calificacion) values (92, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus', 4.9);
insert into FeedBackEntity (id, comentario, calificacion) values (93, 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 2.3);
insert into FeedBackEntity (id, comentario, calificacion) values (94, 'aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 3.6);
insert into FeedBackEntity (id, comentario, calificacion) values (95, 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', 2.9);
insert into FeedBackEntity (id, comentario, calificacion) values (96, 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', 1.7);
insert into FeedBackEntity (id, comentario, calificacion) values (97, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 2.4);
insert into FeedBackEntity (id, comentario, calificacion) values (98, 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 3.3);
insert into FeedBackEntity (id, comentario, calificacion) values (99, 'proin leo odio porttitor id consequat in consequat ut nulla sed', 2.7);
insert into FeedBackEntity (id, comentario, calificacion) values (100, 'amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 2.4);
